---
extends: 'eslint:recommended'
env:
  es6: true
  jest: true
  node: true
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - 0
  comma-dangle:
    - 2
    - objects: always-multiline
