---
extends:
  - eslint:recommended
  - plugin:jest/recommended

plugins:
  - jest

env:
  es6: true
  node: true
  jest: true

parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true

rules:
  comma-dangle: [2, always-multiline]
  indent: [2, 4]
  linebreak-style: [2, unix]
  no-console: 2
  quotes: [2, single]
  semi: [2, always]
